export enum action {
  RESPONSE_FROM_USER = "RESPONSE_FROM_USER",
  SET_RESPONSE_FOR_USER = "SET_RESPONSE_FOR_USER",
  STORE_QUIZ_API_RESPONSE = "STORE_QUIZ_API_RESPONSE",
  SET_USER_EMAIL = "SET_USER_EMAIL",
}
